### PR TITLE
Allow to add custom button actions (or disable already existing ones).

### PR DESCRIPTION
**Pull request by underdpt**
This will allow to create custom button actions, or disable existing ones so they cannot be called by creating a custom request

### CODE REVIEW

**Comment by yajra** [comment]
Released on v1.3.0 🚀 !

BTW, if you can. Please also send a PR for the official docs @ https://github.com/yajra/laravel-datatables-docs. Thanks!

**Comment by underdpt** [comment]
Done:

https://github.com/yajra/laravel-datatables-docs/pull/2

Please be aware English isn't my native language, so a lot of errors are to be expected.

**Comment by yajra** [comment]
Need some CS adjustment and your PR and it's good to go. 

I'm not fluent on English too so I think we should let other users to correct us if we have some grammar issue (lol). ^_^

**Comment by Waguilar33** [comment]
It might be just me but I couldn't for the life of me get this to work.

**Comment by yajra** [comment]
@Waguilar33 on your custom buttons script, you just need to append an `action` column on your request that matches the method on your service class.

**Pull request merged**
